import type { Metadata } from "next";
import { Baloo_2 } from "next/font/google";

import HomeFooter from "@/components/Footers/HomeFooter";
import UserTeacherDashNav from "@/components/Navbars/UserTeacherDashNav";
import UserTeacherDashPad from "@/components/Navbars/UserTeacherDashPad";

const baloo = Baloo_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Responsive Sidebar Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div>
        <UserTeacherDashNav />
        <UserTeacherDashPad />

        {children}
      </div>
    </>
  );
}
