import type { Metadata } from "next";
import { Baloo_2 } from "next/font/google";

import UserStudentDashNav from "@/components/Navbars/UserStudentDashNav";
import UserStudentDashPad from "@/components/Navbars/UserStudentDashPad";
import HomeFooter from "@/components/Footers/HomeFooter";

const baloo = Baloo_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Responsive Sidebar Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div>
        <UserStudentDashNav />
        <UserStudentDashPad />

        {children}
      </div>
    </>
  );
}
