import type { Metadata } from "next";
import { Baloo_2 } from "next/font/google";

import Sidebar from "@/components/sidebars/Sidebar";
import UserStudentDashNav from "@/components/Navbars/UserStudentDashNav";
import Home from "@/app/(home)/page";
import HomeNavbar from "@/components/Navbars/HomeNavbar";

const baloo = Baloo_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Responsive Sidebar Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div>
        <HomeNavbar />

        <main className="min-h-screen">{children}</main>
      </div>
    </>
  );
}
