import type { Metadata } from "next";
import { Baloo_2 } from "next/font/google";

import Sidebar from "@/components/sidebars/Sidebar";
import UserStudentDashNav from "@/components/Navbars/UserStudentDashNav";

const baloo = Baloo_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Responsive Sidebar Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex flex-col h-screen">
        <UserStudentDashNav />

        <div className="flex flex-1 overflow-hidden">
          <Sidebar />
          <main className="flex-1 overflow-y-auto p-4 transition-all duration-300 ease-in-out bg-gray-50 dark:bg-gray-900">
            {children}
          </main>
        </div>
      </div>
    </>
  );
}
