import type { Metadata } from "next";
import { Geist, Geist_Mono, Baloo_Da_2 } from "next/font/google";
import "../globals.css";

import HomeNavbar from "@/components/Navbars/HomeNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div>
        <HomeNavbar />

        <main className="min-h-screen">{children}</main>
      </div>
    </>
  );
}
